# Site settings
title: "Quant Secrets"
email: jordan@quantsecrets.com
description: > # this means to ignore newlines until "baseurl:"
  Learn algorithmic trading.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://quantsecrets.com" # the base hostname & protocol for your site
twitter_username: quantsecrets

logo: /assets/images/header.png
image: /assets/images/header.png

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: ":title/"

# Minification
sass:
  style: compressed